Add API doc generation in CI (close #277)
snowplow/snowplow-python-tracker pull request #278
Opened 2022-07-21 12:26 UTC by Jack-Keene

For issue 277

A Github Workflow that generates the API docs and adds them to the gh-pages branch has been added. The docs can be found here:

http://snowplow.github.io/snowplow-python-tracker/index.html

The docs folder shows in the main repo, I'm not sure if this is an issue?

2022-07-21 18:40 UTC, matus-tomlein requested changes
Looks great, really nice to have good API docs! 👍 

I added a few small comments for you to consider. Also, are you sure that the `docs/_build` folder needs to be added to Git? It seems like the output of the docs generation scripts. In that case, it would be better to remove it and make the repo a bit tidier.

There is one more thing that I have been thinking about – looking at other Spinx docs for Python libs (e.g., for Jinja, Flask), they often have some structure exposing the most useful classes up top for easier navigation. It's not that important as people can search within these docs, but do you think it could be possible to expose links to Tracker, Emitter, Subject, SelfDescribingJson on the front page? For example, [this is how the API page](https://flask.palletsprojects.com/en/2.1.x/api/) for Flask looks like and [here is their rst file](https://raw.githubusercontent.com/pallets/flask/main/docs/api.rst) that generates it. Don't know much about Sphinx, but do you think that we could pick some of the important classes up front like this:

```rst
.. autoclass:: Tracker
   :members:
   :inherited-members:
```

2022-07-21 18:40 UTC, matus-tomlein commented on docs/_build/html/_sources/index.rst.txt
> +Welcome to Snowplow Python Tracker's documentation!
```suggestion
Snowplow Python Tracker API Documentation
```

Welcoming people to a website sounds so 90s 😅

2022-07-21 18:40 UTC, matus-tomlein commented on docs/_build/html/_sources/index.rst.txt
> +
Not that important but could we perhaps paste some short intro what is the tracker here? Maybe just copy the overview from the README, it looks a bit empty. Similar to [the front page of the C++ tracker API docs](https://snowplow.github.io/snowplow-cpp-tracker/).

2022-07-22 13:24 UTC, Jack-Keene commented on snowplow_tracker/celery/celery_emitter.py
> +# """
Sphinx picks up anything with a string and assumes they're part of the docs, which made everything look messy. I'll go through and drop the strings!

2022-08-15 08:40 UTC, matus-tomlein approved these changes
LGTM!

2022-08-16 09:38 UTC, merged