Upgrade set-output in cd (close #294)
snowplow/snowplow-python-tracker pull request #299
Opened 2022-11-11 15:28 UTC by Jack-Keene

This PR updates the soon to be deprecated `set-output` command, described [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

2022-11-11 15:28 UTC, snowplowcla commented
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

2022-11-29 10:50 UTC, jbeemster commented
@snowplowcla check this

2022-12-01 11:46 UTC, rlh1994 requested changes

2022-12-01 11:46 UTC, rlh1994 commented on .github/workflows/cd.yml
> +        echo "##["{name}=PYTHON_TRACKER_VERSION" >> $GITHUB_OUTPUT;]$(python setup.py --version)"
I think it should be this if I understand what it's trying to do correctly...
```suggestion
        echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        echo "PYTHON_TRACKER_VERSION=$(python setup.py --version)" >> $GITHUB_OUTPUT
```

maybe... But I don't really get what that python tracker version line was actually doing before...

2022-12-02 08:54 UTC, rlh1994 approved these changes
LGTM!

2022-12-13 10:53 UTC, merged